added the required roles for the lists and hyperlink buttons
adobe/coral-spectrum pull request #276
Opened 2023-01-25 14:00 UTC by StoianLucian

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

2023-01-25 16:32 UTC, majornista commented on coral-component-buttongroup/src/scripts/ButtonGroup.js
> +            item.setAttribute('role', 'Lists');
"Lists" is not a valid `role` in WAI-ARIA.

2023-01-25 16:33 UTC, majornista commented on coral-component-buttongroup/src/scripts/ButtonGroup.js
> +            item.setAttribute('role', 'Hyperlink');
"Hyperlink" is not a valid `role` in WAI-ARIA.

2023-01-26 13:57 UTC, majornista requested changes
I made a comment on the issue: https://jira.corp.adobe.com/browse/SITES-2948?focusedCommentId=34514063&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-34514063

In ButtonGroup, the appropriate role for a button within the group is determined by the `selectionMode` attribute on the `<coral-buttongroup>` element. You can see an examples of the three possible selection modes here: https://opensource.adobe.com/coral-spectrum/examples/#buttongroup. The issue SITES-2948 relates to the coral-richtexteditor, which used an earlier CloudUI version of the coral-buttongroup, where one needed to explicitly add the `selectionMode="none"` to the component instance.

2023-02-06 09:33 UTC, StoianLucian commented
@majornista i attached the new PRs since i have to make modification in coralui-component-richetexteditor
[master ](https://git.corp.adobe.com/Coral/coralui-component-richtexteditor/pull/271) 
[6.5](https://git.corp.adobe.com/Coral/coralui-component-richtexteditor/pull/270)

2023-02-06 09:34 UTC, closed without merging